# Generated by Django 2.1.2 on 2018-10-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CentroVeterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('horaA', models.DateTimeField()),
                ('horaC', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AdminostradorCentroVeterinario',
            fields=[
                ('nombreUsuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=1000)),
                ('centroVeterinario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CuidadoAnimal.CentroVeterinario')),
            ],
        ),
        migrations.CreateModel(
            name='DescripcionCosto',
            fields=[
                ('costo', models.FloatField(max_length=10)),
                ('descripcion', models.CharField(max_length=30)),
                ('casos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CuidadoAnimal.Casos')),
            ],
        ),
        migrations.CreateModel(
            name='DuenoMascota',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CuidadoAnimal.Usuario')),
                ('direccion', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
            ],
            bases=('CuidadoAnimal.usuario',),
        ),
        migrations.CreateModel(
            name='MedicoVeterinario',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CuidadoAnimal.Usuario')),
                ('especialidad', models.CharField(max_length=20)),
            ],
            bases=('CuidadoAnimal.usuario',),
        ),
        migrations.AddField(
            model_name='servicio',
            name='centroVeterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuidadoAnimal.CentroVeterinario'),
        ),
        migrations.AddField(
            model_name='palabraclave',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuidadoAnimal.Servicio'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuidadoAnimal.Mascota'),
        ),
        migrations.AddField(
            model_name='casos',
            name='hClinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuidadoAnimal.HistoriaClinica'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='cVeterinario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CuidadoAnimal.CentroVeterinario'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuidadoAnimal.DuenoMascota'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuidadoAnimal.DuenoMascota'),
        ),
    ]
